model:
  classes: 20
  input_size: [512,256] # size of the network input
  architecture: "A"

  weights: "frrn.h5"

train:
  batch_size: 2
  steps_per_epoch: 1000
  epochs: 10
  validation_steps: 100


  augmenter:
    crop_probability: 0.3
    blur_probability: 0.1
    affine_probability: 0.5


  dataset:
    name: "cityscapes"
    path: "/media/fabi/a5c9fb71-4a59-421d-82a0-49a31c2b3013/datasets/cityscapes"

  preprocessor:
    input_size: [512,256] # size of the network input


evaluate:
  dataset:
    name: "cityscapes"
    path: "/media/fabi/a5c9fb71-4a59-421d-82a0-49a31c2b3013/datasets/cityscapes"

  eval_dir: "eval"


  preprocessor:
    input_size: [512,256] # size of the network input
